name: Checks

on: [push]

jobs:
  test-lint:
    runs-on: ubuntu-24.04
    env:
      USE_SQLITE_FOR_TESTS: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image with dev deps
        run: docker compose build --build-arg DEV=true app

      - name: Grant MySQL permissions
        run: |
          docker compose up -d db

          echo "Waiting for MySQL to be ready..."
          until docker compose exec -T db mysqladmin ping -h 127.0.0.1 -u root -prootpass --silent; do
            sleep 2
          done

          echo "Granting privileges..."
          docker compose exec -T db mysql -h 127.0.0.1 -u root -prootpass -e "
          GRANT ALL PRIVILEGES ON *.* TO 'devuser'@'%';
          FLUSH PRIVILEGES;
          "
      

      - name: Run Tests
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Run Lint
        run: docker compose run --rm app sh -c "flake8"
